name: SimpCity CI on Pull Requests

on:
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install pytest coverage pytest-cov
    - name: Run tests and collect coverage
      run: |
        cd test; pytest --cov -v --junitxml=report.xml
    - name: Build coverage file
      run: |
        pytest --cache-clear --cov -v --cov=SimpCity test/ > pytest-coverage.txt
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: pytest-coverage.txt
